@extends('layouts.dashboard')
@section('content')
<div class="dashboard-page review-monitoring-page"><header class="dashboard-page-heading dashboard-page-heading-row"><div><h1>Reviewer Assignments</h1><p>{{ $reviewer->name }}</p></div><a class="dashboard-outline-action" href="{{ route('res.review-monitoring.index').'#review-monitoring-capacity' }}"><x-dashboard.icon name="arrow-left" size="17" /><span>Back to Monitoring</span></a></header>
<form class="application-panel monitoring-drilldown-filters monitoring-drilldown-filters-wide unified-filter-panel" method="GET">
<x-dashboard.filter-header description="Refine this Reviewer's assignments." :reset-href="url()->current()" />
<div class="unified-filter-fields">
<div class="application-field application-search-field"><label for="reviewer-assignment-q">Search</label><span><x-dashboard.icon name="search" size="18" /></span><input id="reviewer-assignment-q" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Application code or research title"></div>
<div class="application-field"><label for="reviewer-assignment-term">Academic Term</label><select id="reviewer-assignment-term" name="academic_term_id"><option value="">All</option>@foreach($termOptions as $term)<option value="{{ $term->id }}" @selected((string)($filters['academic_term_id'] ?? '') === (string)$term->id)>{{ $term->filterLabel() }}</option>@endforeach</select></div>
<div class="application-field"><label for="reviewer-review-type">Review Type</label><select id="reviewer-review-type" name="review_type"><option value="">All review types</option>@foreach(['expedited'=>'Expedited','full_board'=>'Full Board','revision_review'=>'Revision Review'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['review_type'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="application-field"><label for="reviewer-assignment-status">Status</label><select id="reviewer-assignment-status" name="assignment_status"><option value="">All statuses</option>@foreach(\App\Enums\ReviewerAssignmentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(($filters['assignment_status'] ?? '') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
<div class="application-field"><label for="reviewer-date-from">Assigned From</label><input id="reviewer-date-from" name="date_from" type="date" value="{{ $filters['date_from'] ?? '' }}"></div><div class="application-field"><label for="reviewer-date-to">Assigned To</label><input id="reviewer-date-to" name="date_to" type="date" value="{{ $filters['date_to'] ?? '' }}"></div></div></form>
<section class="application-panel review-monitoring-panel" aria-labelledby="reviewer-assignment-table-title"><header class="application-panel-heading"><div><h2 id="reviewer-assignment-table-title">All Assignments</h2></div><span>{{ $assignments->total() }} total</span></header>@if($assignments->isEmpty())<x-dashboard.empty-state image="no-applications" alt="No reviewer assignments" title="No assignments found" message="No assignments match the selected filters." />@else<x-dashboard.overflow label="Reviewer assignment records" wide><table class="dashboard-table monitoring-drilldown-table"><thead><tr><th>Application</th><th>Academic Term</th><th>Review Type</th><th>Assignment Status</th><th>Assigned</th><th class="dashboard-table-action">Action</th></tr></thead><tbody>@foreach($assignments as $assignment)@php($application=$assignment->researchApplication)<tr><td><strong>{{ $application?->application_code }}</strong><small class="monitoring-title-truncate" data-research-title-tooltip>{{ $application?->research_title }}</small></td><td>{{ $application?->academicTerm?->label() ?? 'Unassigned term' }}</td><td>{{ filled($application?->review_type) ? Str::headline($application->review_type) : Str::headline($assignment->review_type) }}</td><td><x-dashboard.status-badge :label="$assignment->assignment_status->label()" :tone="$assignment->assignment_status->tone()" /></td><td>{{ $assignment->assigned_at?->format('M j, Y') ?? 'Not recorded' }}</td><td class="dashboard-table-action"><x-dashboard.action-link :href="route('res.applications.show', $application)">View</x-dashboard.action-link></td></tr>@endforeach</tbody></table></x-dashboard.overflow><x-dashboard.pagination :paginator="$assignments" label="Reviewer assignment pages" />@endif</section></div>
@endsection
